### PR TITLE
upgraded to Javalin 3.5.0

### PR DESCRIPTION
**Pull request by schmas**

### CODE REVIEW

**Comment by leleuj** [comment]
You also may want to update the README to meet some reference one: https://github.com/pac4j/jee-pac4j

**Comment by leleuj** [comment]
Keep me posted when you need a release...

**Comment by schmas** [comment]
> You also may want to update the README to meet some reference one: https://github.com/pac4j/jee-pac4j

Sorry, but what do mean by that?

**Comment by schmas** [comment]
> Keep me posted when you need a release...

Whenever you can. I'm already building a project that I will need that. Thanks.

**Comment by leleuj** [comment]
About the README, I meant having almost the same text, sections, explanations... I also meant having some pages in the wiki with the release notes...

About the release, it's done. The artifact will show up soon in the Maven central repo.

**Pull request merged**
