### PR TITLE
Module info

### PR DESCRIPTION
**Pull request by trensetim**
https://github.com/pac4j/javalin-pac4j/issues/100

### CODE REVIEW

**Comment by leleuj** [comment]
Yes, but no. Don't downgrade the pac4j version. Use `pac4j-jee` instead of `pac4j-core`...

**Comment by trensetim** [comment]
Nice hint. Didn't knew of that one. Will fix it this evening and make another pull request

**Comment by leleuj** [comment]
You can do everything in the same PR. It will be easier I think.

**Comment by trensetim** [comment]
Well just adding pac4j-jee does not solve the issue, because then the package org.pac4j.core.http.adapter is a split package between the modules pac4j-core and pac4-jee. As I see it, JEE is not strictly necessary here (or is it?). So I'd go for replacing JEE-specifics with implementations of the core-interfaces, thus eliminating the need to depend on jee entirely and avoiding the split package.
As I read it, split packages across different modules are a sign of not having defined the boundaries right... Maybe pac4j needs to consider repackaging their classes. But in the meantime, I'll go with circumventing that.

**Comment by trensetim** [comment]
I was wondering whether we should increment the version number, since removing jee will change JavalinWebContext from extending JEEWebContext to implementing WebContext directly. Whats your opinion on this?

**Comment by trensetim** [comment]
> Well just adding pac4j-jee does not solve the issue, because then the package org.pac4j.core.http.adapter is a split package between the modules pac4j-core and pac4-jee. As I see it, JEE is not strictly necessary here (or is it?). So I'd go for replacing JEE-specifics with implementations of the core-interfaces, thus eliminating the need to depend on jee entirely and avoiding the split package. As I read it, split packages across different modules are a sign of not having defined the boundaries right... Maybe pac4j needs to consider repackaging their classes. But in the meantime, I'll go with circumventing that.

This actually true even if I replace pac4j-core by pac4j-jee because ~jee depends on ~core.

**Comment by trensetim** [comment]
Please do not accept this pull request.

Although it will compile, it will pose the requirement on the library users to themselfes depend on javax.servlet.api and it will furthermore break the class hierarchy (which SHOULD not change anything for users, because those intermediate JEE classes seem to be private implementation detail, from my perspective, BUT one can never know....)

I created another branch in which I did not try to create a module-info, but instead use an Automatic-Module-Name. That works flawless for me using it, so we should rather use that one.

**Pull request closed without merging**
