### PR TITLE
Automatic module name

### PR DESCRIPTION
**Pull request by trensetim**
https://github.com/pac4j/javalin-pac4j/issues/100

### CODE REVIEW

**Comment by leleuj** [comment]
Just a few explanations here about `pac4j-core` and `pac4j-jee`.

`pac4j` is agnostic from any framework, it is a generic security engine. Though, as the JEE environment is used in many web frameworks, JEE implementations were in the `pac4j-core` dependency and are now in the `pac4j-jee` dependency. Preparing the arrival of the `pac4-jakartaee` dependency.

**Comment by trensetim** [comment]
I wonder if it was worth incrementing the patch version number for this and make another release?

**Comment by leleuj** [comment]
Yes, it should be a new minor version. I shouldn't have upgraded to pac4j v5.3 without updating the dependency and the version.
The master is now fixed at `4.1.0-SNAPSHOT`.

Though, I can't cut a release. The build fails when using `mvn clean package`.

**Comment by leleuj** [comment]
You can now see the build failure in the Github Actions CI workflow: https://github.com/pac4j/javalin-pac4j/actions/runs/1909063293

**Comment by trensetim** [comment]
Finally I found time to investigate this.
The build fails, because the maven-javadoc-plugin runs with usage of the module system. Since Pac4J-JEE is not correctly modularized (having split packages with pac4j-core all over the place), I do not see any chance of getting this to work correctly.
Because including javalin-pac4j will mean for the user to transitively include pac4j-jee this will remain an issue for end users, even if we got the build to succeed, since then the builds of the library users will ultimately fail probably.

One could try running maven-javadoc-plugin without module support possibly. I did not try this, because it seems like a bad workaround.

Since I do not see this to work while including pac4j-jee, I will continue investigating whether dropping pac4j-jee could be an option. Even if this MAY SLIGHTLY impact the user and thus be a candidate for a new major version.
So I will reconsider https://github.com/pac4j/javalin-pac4j/pull/101 .... (but remain in thiss pull request now)

**Comment by leleuj** [comment]
In fact, other pac4j implementations (like jee-pac4j) use pac4j-jee and the problem does not show up: https://github.com/pac4j/jee-pac4j/blob/master/pom.xml#L63
So there must be something different in the case of javalin-pac4j.

**Comment by trensetim** [comment]
The mentioned project is not modularized. It neither has an Automatic-Module-Name nor a module-info.java.
I have cloned the repo and added an Automatic-Module-Name, resulting in a build break too.... So the same problem there.

I have made another fork of javalin-pac4j and tried adding a module-info.java here https://github.com/trensetim/javalin-pac4j/commit/191ec1c4c5035f98970c2aed4b07523df6c8334b

That did not go so well either, so I am kind of stuck. My best hope currently is to wait for javalin to upgrade jetty such that jetty uses jakarta instead of javax. That would resolve the issue I have explained in the mentioned commit.

If you have any other ideas, please let me know. For the time being, my plan is to postpone this until javalin was updated.

**Comment by leleuj** [comment]
You're right: everything comes from the module concept in Java. It does not support split packages.
I haven't been able to find a solution too.
I think the only option is to avoid split packages in pac4j itself. I'll keep you posted.

**Comment by leleuj** [comment]
@trensetim I have updated pac4j itself.
Can you set the `javalin-pac4j` version to 5.0.0-SNAPSHOT (breaking change) and upgrade to `pac4j-javaee` 5.4.0-SNAPSHOT (instead of `pac4j-jee`) and change the package reference (JEE components are now in the `org.pac4j.jee` package)? Thanks

**Comment by leleuj** [comment]
I just did it by myself. The build is fixed. Can you confirm it's ok for you before I release? Thanks

**Pull request merged**
